### ISSUE TITLE
osmcount hat eine Pause verdient

### ISSUE THREAD

**Issue by mmd-osm** [TheFive/osmcount#29]
Da die DB auf der dev-Instanz momentan nicht aktualisiert wird, ist der jede Nacht eingeplante Job nicht so wirklich zielführend.

**Comment by TheFive** [comment]
:-) ich stell den Dienst mal ab....
Ich glaube nicht nur eine Pause auch ein "Fresh" Up.

Könnte nach OSMCAL mein nächstes Projekt werden.
